version: 0.2

phases:
  install:
    commands:
      # - npm i npm@latest -g
      - curl -s https://deb.nodesource.com/setup_16.x | sudo bash
      - yum install -y nodejs
      - node -v
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - rm package-lock.json
      - npm install
  build:
    commands:
      - echo Build Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./dist s3://saju-front-prod-0723
